version: '2'

services:
  mysql:
    image: mysql/mysql-server:5.6
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment: 
      - MYSQL_USER=notes-api
      - MYSQL_PASSWORD=notes-api
      - MYSQL_DATABASE=notes
      - MYSQL_ROOT_PASSWORD=root
    volumes:
       - db-data:/var/lib/mysql
       - ./database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql
       - /var/run/mysqld/mysqld.sock

  node:
    build: ./nodejs/.
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    image: nginx:1.9
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

volumes:
  db-data: